window.scheduleDatabase = {
  campuses: [
    {
      id: "gwangjin",
      name: "광진캠퍼스",
      olympiadName: "광진캠퍼스",
      location: "서울특별시",
      redirectSites: {
        math: "https://math.olympiad.ac",
        english: "https://www.glec.co.kr",
      },
    },
    {
      id: "seongdong",
      name: "성동캠퍼스",
      olympiadName: "성동캠퍼스",
      location: "서울특별시",
      redirectSites: {
        math: "https://math.olympiad.ac",
        english: "https://www.glec.co.kr",
      },
    },
    {
      id: "dongdaemun",
      name: "동대문캠퍼스",
      olympiadName: "동대문캠퍼스",
      location: "서울특별시",
      redirectSites: {
        math: "https://math.olympiad.ac",
        english: "https://www.glec.co.kr",
      },
    },
    {
      id: "jungnang",
      name: "중랑캠퍼스",
      olympiadName: "중랑캠퍼스",
      location: "서울특별시",
      redirectSites: {
        math: "https://math.olympiad.ac",
        english: "https://www.glec.co.kr",
      },
    },
    {
      id: "songpa",
      name: "송파방이캠퍼스",
      olympiadName: "송파방이캠퍼스",
      location: "서울특별시",
      redirectSites: {
        math: "https://www.u2math.co.kr",
      },
    },
    {
      id: "junggye",
      name: "중계캠퍼스",
      olympiadName: "중계캠퍼스",
      location: "서울특별시",
      redirectSites: {
        math: "https://www.u2math.co.kr",
      },
    },
    {
      id: "misa",
      name: "미사캠퍼스",
      olympiadName: "미사캠퍼스",
      location: "경기도",
      redirectSites: {
        math: "https://www.u2math.co.kr",
      },
    },
  ],

  subjects: [
    {
      id: "math",
      name: "수학",
      olympiadName: "수학",
      campusIds: ["gwangjin", "seongdong", "dongdaemun", "jungnang", "songpa", "junggye", "misa"],
      unavailableSaturdayCampusIds: ["gwangjin"],
    },
    {
      id: "english",
      name: "영어",
      olympiadName: "영어",
      campusIds: ["gwangjin", "seongdong", "dongdaemun", "jungnang"],
      unavailableSaturdayCampusIds: [],
    },
    {
      id: "math_english",
      name: "수학+영어",
      olympiadName: "수학+영어",
      campusIds: ["gwangjin", "seongdong", "dongdaemun", "jungnang"],
      unavailableSaturdayCampusIds: [],
    },
  ],

  scheduleRules: {
    basic: [
      {
        campuses: ["전체"],
        weekdays: ["월~금"],
        subjects: ["전체"],
        gradeGroups: ["전체"],
        status: "신청가능",
        times: ["14:00", "15:00", "16:00", "17:00", "18:00", "19:00"],
      },
      {
        campuses: ["전체"],
        weekdays: ["토"],
        subjects: ["전체"],
        gradeGroups: ["전체"],
        status: "신청가능",
        times: ["11:00", "12:00", "13:00", "14:00", "15:00"],
      },
      {
        campuses: ["전체"],
        weekdays: ["일"],
        subjects: ["전체"],
        gradeGroups: ["전체"],
        status: "휴무",
        times: [],
      },
      {
        campuses: ["광진"],
        weekdays: ["토"],
        subjects: ["수학"],
        gradeGroups: ["전체"],
        status: "휴무",
        times: [],
      },
    ],
    special: [
      {
        date: "2026-08-17",
        campuses: ["전체"],
        subjects: ["전체"],
        gradeGroups: ["전체"],
        status: "휴무",
        times: [],
      },
      ...["2026-08-22", "2026-08-29"].flatMap((date) => [
        {
          date,
          campuses: ["광진", "성동", "동대문", "중랑"],
          subjects: ["수학"],
          gradeGroups: ["초등", "중등"],
          status: "신청가능",
          times: ["12:00"],
        },
        {
          date,
          campuses: ["광진", "성동", "동대문", "중랑"],
          subjects: ["영어"],
          gradeGroups: ["초등", "중등"],
          status: "신청가능",
          times: ["11:00"],
        },
        {
          date,
          campuses: ["광진", "성동", "동대문", "중랑"],
          subjects: ["전체"],
          gradeGroups: ["고등"],
          status: "신청가능",
          times: ["14:00"],
        },
        {
          date,
          campuses: ["미사"],
          subjects: ["수학"],
          gradeGroups: ["초등", "중등"],
          status: "신청가능",
          times: ["11:00"],
        },
        {
          date,
          campuses: ["미사"],
          subjects: ["수학"],
          gradeGroups: ["고등"],
          status: "신청가능",
          times: ["14:00"],
        },
        {
          date,
          campuses: ["중계"],
          subjects: ["수학"],
          gradeGroups: ["전체"],
          status: "신청가능",
          times: ["14:00"],
        },
        {
          date,
          campuses: ["송파방이"],
          subjects: ["수학"],
          gradeGroups: ["전체"],
          status: "신청가능",
          times: ["11:00"],
        },
      ]),
    ],
  },
};
